#
# global configuration
#

# building
source: .
destination: build
unpublished: false
lsi: true
incremental: true

title: CoderDojo Belgium Gembloux

# plugins
plugins:
  - jekyll-default-layout
  - jekyll-relative-links
#  - jekyll-paginate
  - jekyll-seo-tag

markdown: kramdown

sass:
  style: compressed

relative_links:
  enabled:     true
  collections: false

# content related
description: >
  Site web du CoderDojo Belgium Gembloux.
repository: https://github.com/CoderDojoBelgiumGembloux/coderdojobelgiumgembloux.github.io
baseurl: /
url: https://coderdojobelgiumgembloux.github.io

navigation:
  - text: CoderDojo Belgium Gembloux
    url: /

exclude:
  - "README.md"
  - "Gemfil*"
  - "LICENSE"
  - vendor
  - TODO.md

#paginate: 10
permalink: pretty
